BASE_URL = "https://stellarburgers.nomoreparties.site"
USER_REGISTER_URL = f"{BASE_URL}/api/auth/register"
USER_LOGIN_URL = f"{BASE_URL}/api/auth/login"
USER_URL = f"{BASE_URL}/api/auth/user"
INGREDIENTS_URL = f"{BASE_URL}/api/ingredients"
ORDERS_URL = f"{BASE_URL}/api/orders"
